### PR TITLE
Update to alloy5

### PR DESCRIPTION
**Pull request by jeffbolznv**
We've found that expressions like '#dr>0' don't always evaluate correctly.
This seems to be fixed in Alloy5.

### CODE REVIEW

**Comment by nhaehnle** [comment]
Could you please double-check the line breaks? The commit shows as introducing a mix of DOS- and Unix-style line breaks throughout the modified text files.

Apart from that, it looks good to me.

**Comment by jeffbolznv** [comment]
Thanks. I fixed the RunCommandLine.java line endings, but I couldn't find issues in the other files.

**Comment by nhaehnle** [comment]
Here's what I'm seeing on Linux after a fetch of the branch and a `git show`:
```
diff --git a/README.md b/README.md
index e94f62e..05cff33 100644
--- a/README.md
+++ b/README.md
@@ -8,6 +8,19 @@ Other Khronos-maintained specifications and software projects that have been
 extended to support this model are listed in the
 [extension release checklist](https://github.com/KhronosGroup/Vulkan-Docs/issues/787).
 
+## Alloy Model^M
+^M
+The [alloy](alloy) subdirectory includes an^M
+[Alloy](http://alloy.lcs.mit.edu/alloy/index.html) [implementation](alloy/spirv.als)^M
+of the memory model, a set of [litmus tests](alloy/tests) written in a^M
+rudimentary syntax, [C++ source](alloy/litmus.cpp) for a tool to translate^M
+the litmus tests to alloy, and a [makefile](alloy/Makefile) to execute the^M
+tests. A java class to run the alloy tests is compiled against^M
+https://oss.sonatype.org/content/repositories/snapshots/org/alloytools/org.alloytools.alloy.dist/5.0.0-SNAPSHOT/org.alloytools.alloy
.dist-5.0.0-20190619.101010-34.jar.^M
+Download this jar file and place it in the [alloy](alloy) subdirectory.^M
+Simply run "make -j4" from the [alloy](alloy) subdirectory to run the^M
+tests. Required dependencies are just g++, GNU make, alloy, and a Java runtime.^M
+^M
 ## License
 
 This repo is treated as an offshoot of the Vulkan-Docs repo, and uses the
```
And:
```
diff --git a/alloy/Makefile b/alloy/Makefile
index 863754f..40d1a61 100644
--- a/alloy/Makefile
+++ b/alloy/Makefile
@@ -1,4 +1,4 @@
-# Copyright (c) 2017-2018 Khronos Group. This work is licensed under a
+# Copyright (c) 2017-2019 Khronos Group. This work is licensed under a^M
 # Creative Commons Attribution 4.0 International License; see
 # http://creativecommons.org/licenses/by/4.0/
 
@@ -21,7 +21,7 @@ Assert%: pre
        @echo "$@"
        @printf "open spirv\ncheck $@ for 8 but 1 Exec" > build/$@.als
        @echo "NOSOLUTION" > build/$@.ref
-       @java -cp "alloy4.2_2015-02-22.jar$(JAVACPSEPARATOR)." RunCommandLine build/$@.als > build/$@.out
+       @java -cp "org.alloytools.alloy.dist-5.0.0-20190619.101010-34.jar$(JAVACPSEPARATOR)." RunCommandLine build/$@.als > build/$@.out^M
        @diff --strip-trailing-cr build/$@.ref build/$@.out || echo "Test $@ failed"
 
 asserts: AssertLocordSameLoc AssertLocordAcyclic AssertLocordComplete1 AssertLocordComplete2 AssertVisTo
@@ -55,5 +55,5 @@ endif
        $(eval test = $(notdir $<))
        @echo $(test)
        @./build/litmus.exe $(test) tests build
-       @java -cp "alloy4.2_2015-02-22.jar$(JAVACPSEPARATOR)." RunCommandLine build/$(test).gen > build/$(test).out
+       @java -cp "org.alloytools.alloy.dist-5.0.0-20190619.101010-34.jar$(JAVACPSEPARATOR)." RunCommandLine build/$(test).gen > build/$(test).out^M
        @diff --strip-trailing-cr build/$(test).ref build/$(test).out || echo "Test $@ failed"
```
Note the various ^M. I don't see any non-standard linebreak-related settings in my git config.

**Comment by jeffbolznv** [comment]
I've run dos2unix on these two files and pushed a new commit. Let me know if it helps.

What's your setting of core.autocrlf?

**Comment by jeffbolznv** [comment]
Hmm, github shows those files and completely different now, so I don't think that was the right fix. I'd like to revert it, but let's at least see if it fixes it on your side first.

**Comment by jeffbolznv** [comment]
I reverted the dos2unix commit and merged the change.

**Pull request merged**
